### PR TITLE
minor details

### PR DESCRIPTION
**Pull request by fchapoton**

### CODE REVIEW

**Comment by jviusos** [comment]
Dear @fchapoton, thak you for your corrections in the code.

Just a silly question, is there any computational reason for expressing as condition `not ell % d` instead of `d.divides(ell)`? The first one seems less "straightforward readable" in the code.

Bests,
Juan

**Comment by fchapoton** [comment]
Well, the method divides is only available for sage integers, I think. The modulo `%` is pure python.

**Comment by jviusos** [comment]
Ok, should this be an issue somehow?

**Comment by fchapoton** [comment]
I am not sure to understand what you ask. My proposal is slightly more efficient and works as well for sage integers and for python integers.

**Comment by jviusos** [comment]
Ok, thanks. This is what I was asking for, if this was really "an improvement" in terms of efficiency .

**Pull request merged**
